blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('post.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)


blog/post/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

app_name = 'app_post'

urlpatterns = [
    path('', views.homePage, name='home'),
    path('<int:pk>', views.post, name='post'),
    path('blogs', views.blog, name='blogs'),
    path('contact', views.contact, name='contact'),
]
urlpatterns += staticfiles_urlpatterns()




blog/post/models.py
from django.db import models
from ckeditor.fields import RichTextField

    
class BlogPost(models.Model):
    post_title = models.CharField(max_length=255)
    post_thumbnail = models.ImageField(blank=True, null=True, upload_to='images/')
    post_para = models.CharField(max_length=255, default='mani')
    post_created = models.DateTimeField(auto_now_add=True)
    post_updated = models.DateTimeField(auto_now=True)
    body = RichTextField()
    
    def __str__(self):
        return self.post_title

blog/post/views.py
from django.shortcuts import render
from .models import BlogPost


def homePage(request):
    posts = BlogPost.objects.order_by('post_created')[:5]
    context = {'posts': posts}
    return render(request, 'post/home.html', context)


def post(request, pk):
    posts = BlogPost.objects.order_by('-post_created')[:3]
    selected_post = BlogPost.objects.get(pk=pk)
    context = {'selected_post': selected_post, 'posts': posts}
    return render(request, 'post/post.html', context)

def blog(request):
    blogs = BlogPost.objects.order_by('-post_created')[:20]
    context = {'blogs': blogs}
    return render(request, 'post/blogs.html', context)

def contact(request):
    return render(request, 'post/contact.html', {})

blog/post/templates/post/blogs.html
{% extends 'main.html' %} {% load static %} {% block content %}
<section class="container" id="blog">
  <h1>Explore My world of words: My complete blog archive</h1>
  <div id="blog-list">
    {% for blog in blogs%}
    <article>
      <a href="{% url 'app_post:post' blog.id%}">
        <div class="blog-img">
          <img src="{{blog.post_thumbnail.url}}" alt="" />
        </div>
        <div class="blog-body">
          <h1 id="article-heading">{{blog.post_title}}</h1>
          <p>{{blog.post_para|truncatechars:150}}</p>
          <div class="post-date">
            <span>{{blog.post_created.date}}</span>
          </div>
        </div>
      </a>
    </article>
    {% endfor %}
  </div>
</section>
{% endblock %}

blog/post/templates/post/home.html
{% extends 'main.html' %} {%load static %} {%block content %}
<section id="hero" class="container">
  <div id="hero-img">
    <img src="{% static 'media/author.png' %}" alt="" />
  </div>
  <div id="hero-text">
    <p>
      I'm Mani, a passionate <span>Full Stack developer</span> with experience
      in front-end and back-end development. Proficient in languages such as
      HTML, CSS, JavaScript, Python and Django, I have the skills necessary to
      create stunning websites and web applications. My attention to detail,
      creativity, and dedication ensure that each project I work on is a
      success. Let's work together to bring your ideas to life!
    </p>
    <a href="{% url 'app_post:contact' %}" id="cta-btn">Get in Touch</a>
  </div>
</section>
<section class="container" id="blog">
  <h1>New Releases</h1>
  <div id="blog-list">
    {% for post in posts%}
    <article>
      <a href="{% url 'app_post:post' post.id%}">
        <div class="blog-img">
          <img src="{{post.post_thumbnail.url}}" alt="" />
        </div>
        <div class="blog-body">
          <h1 id="article-heading">{{post.post_title}}</h1>
          <p>{{post.post_para|truncatechars:150}}</p>
          <div class="post-date">
            <span>{{post.post_created.date}}</span>
          </div>
        </div>
      </a>
    </article>
    {% endfor %}
  </div>
</section>
{% endblock %}

blog/post/templates/post/post.html
{% extends 'main.html' %} {% load static %} {% block content %}
<section id="post-container">
  <div class="post">
    <div class="post-content">
      <h1>{{selected_post.post_title}}</h1>
      <div class="post-body">
        <p class="post-para">{{selected_post.body|safe}}</p>
      </div>
    </div>
    <div class="sidebar">
      {% for post in posts%}
      <article>
        <a href="{% url 'app_post:post' post.id %}">
          <div class="blog-img">
            <img src="{{post.post_thumbnail.url}}" alt="" />
          </div>
          <div class="blog-body">
            <h1 id="article-heading">{{post.post_title}}</h1>
            <p>{{post.post_para|truncatechars:150}}</p>
            <div class="post-date">
              <span>{{post.post_created.date}}</span>
            </div>
          </div>
        </a>
      </article>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock content %}

blog/templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Mani-Full Stack Wizard</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <script
      src="https://kit.fontawesome.com/83a59ffa44.js"
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>

blog/templates/navbar.html
{%load static %}

<header>
  <div id="logo">
    <a href="{% url 'app_post:home' %}"><i class="fa-solid fa-m"></i></a>
  </div>
  <div id="hamburger-icon" onclick="openMenuBar()">
    <p href="#"><i class="fa-solid fa-bars"></i></p>
  </div>
  <nav id="navbar">
    <ul>
      <p href="#" onclick="closeMenuBar()" id="crossbar-icon">X</p>
      <li><a href="{% url 'app_post:home' %}">Home</a></li>
      <li><a href="{% url 'app_post:blogs' %}">Articles</a></li>
      <li><a href="{% url 'app_post:contact' %}">Contact</a></li>
      <li>
        <a href="mailto:orewazorodha@gmail.com"
          ><i class="fa-regular fa-envelope"></i
        ></a>
      </li>
    </ul>
  </nav>
</header>